# Generated by Django 4.2.2 on 2023-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terzoneexist',
            name='kind_obj',
            field=models.IntegerField(),
        ),
    ]
