# Generated by Django 4.2.2 on 2023-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0002_change_terzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terzoneexist',
            name='kind_obj',
            field=models.IntegerField(null=True),
        ),
    ]

