# Generated by Django 4.2.2 on 2023-08-24 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0003_change_field_terzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terzoneexist',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
