# Generated by Django 4.2.2 on 2023-08-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0005_create_kind_terzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Archived'), (1, 'Available')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind_terzone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planreg', to='terzone.kindterzone')),
            ],
        ),
    ]
