# Generated by Django 4.2.2 on 2023-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0007_add_field_index_planreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planregulation',
            name='status',
        ),
        migrations.AddField(
            model_name='planregulation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
