# Generated by Django 4.2.2 on 2023-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0008_change_fields_planreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='planregulation',
            name='terzones',
            field=models.ManyToManyField(related_name='planregs', to='terzone.terzoneexist'),
        ),
    ]
