# Generated by Django 4.2.2 on 2023-08-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0009_add_field_terzones_planreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terzoneexist',
            name='kind_obj',
        ),
        migrations.AddField(
            model_name='terzoneexist',
            name='kind_terzone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terzoneexist', to='terzone.kindterzone'),
        ),
    ]
