# Generated by Django 4.2.2 on 2023-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0010_add_field_kind_terzone_terzoneexist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terzoneexist',
            name='status',
            field=models.IntegerField(choices=[(1, 'Archived'), (0, 'Available')]),
        ),
    ]
