# Generated by Django 4.2.2 on 2023-08-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terzone', '0011_change_field_status_terzoneexist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planregulation',
            name='kind_terzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planreg', to='terzone.kindterzone'),
        ),
    ]
